apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: drupal-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: drupal-hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
