apiVersion: v1
kind: Service
metadata:
  labels:
    app: flatris
  name: flatris
  namespace: default 
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: flatris    
  type: NodePort