apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: joomla
  name: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joomla
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: joomla
    spec:
      containers:
      - image: joomla:latest
        name: joomla
        resources: {}
        ports:
          - containerPort: 80
        command: ["/bin/bash", "-c" ]
        args: ["cp -r /usr/src/joomla/* /var/www/html && php installation/joomla.php install --site-name=joomladev --admin-user=admin --admin-username=admin --admin-password=kube-still-rocks --admin-email=admin@example.com --db-type=mysql --db-host=mariadb --db-user=admin --db-pass=kube-still-rocks --db-name=myDB && apache2-foreground"]
        envFrom:
        - secretRef:
            name: joomla-env
status: {}