apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend-service
  name: frontend
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    tier: front
  type: NodePort