---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
   tier: front
spec:
  containers:
    - name: nginx
      image: nginx:alpine3.18-perl
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
   tier: front
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
      - containerPort: 80